CREATE PROCEDURE ideal_pay_by_deps

PARAMETERS PeriodID Long, MtdID Long, PayTypePropID Long;
SELECT AGENTS.AG_VATNO, AG_PROPS.PROP_LONG, P_JOURNAL.W_PERIOD, P_PERIOD.PP_MONTH, P_PERIOD.PP_YEAR, Sum(P_JOURNAL.JP_SUM) AS MtdSum
FROM P_PERIOD RIGHT JOIN ((AGENTS LEFT JOIN AG_PROPS ON AGENTS.AG_ID = AG_PROPS.EL_ID) RIGHT JOIN (MTD_DEPENDS LEFT JOIN P_JOURNAL ON MTD_DEPENDS.MTD_ID_LEFT = P_JOURNAL.MTC_ID) ON AGENTS.AG_ID = P_JOURNAL.AG_ID) ON P_PERIOD.PP_ID = P_JOURNAL.W_PERIOD
GROUP BY AGENTS.AG_VATNO, AG_PROPS.PROP_LONG, P_JOURNAL.W_PERIOD, P_PERIOD.PP_MONTH, P_PERIOD.PP_YEAR, P_JOURNAL.C_PERIOD, P_JOURNAL.JP_DONE, MTD_DEPENDS.MTD_ID_RIGHT, AG_PROPS.PROP_ID
HAVING (((Sum(P_JOURNAL.JP_SUM))<>0) AND ((P_JOURNAL.C_PERIOD)=[PeriodID]) AND ((P_JOURNAL.JP_DONE)=1) AND ((MTD_DEPENDS.MTD_ID_RIGHT)=[MtdID]) AND ((AG_PROPS.PROP_ID)=[PayTypePropID]));

END

CREATE PROCEDURE ideal_sum_by_ag_mtc_period

SELECT AGENTS.AG_VATNO, P_JOURNAL.MTC_ID, Sum(P_JOURNAL.JP_SUM) AS [Sum-JP_SUM]
FROM AGENTS INNER JOIN P_JOURNAL ON AGENTS.AG_ID = P_JOURNAL.AG_ID
WHERE (((P_JOURNAL.JP_DONE)=1) AND ((P_JOURNAL.C_PERIOD)=[PeriodID]))
GROUP BY AGENTS.AG_VATNO, P_JOURNAL.MTC_ID;

END