Create procedure Rep_tabel
PARAMETERS pid long, dno text;
SELECT DISTINCT P_JOURNAL.AG_ID AS agid, AGENTS.AG_NAME
FROM P_DOCUMENTS INNER JOIN (AGENTS INNER JOIN P_JOURNAL ON AGENTS.AG_ID = P_JOURNAL.AG_ID) ON P_DOCUMENTS.PD_ID= P_JOURNAL.PD_ID
WHERE P_JOURNAL.C_PERIOD=pid AND P_JOURNAL.JP_SUM<>0 AND P_DOCUMENTS.PD_NO = dno
ORDER BY AGENTS.AG_NAME;
END

Create procedure Rep_total
PARAMETERS advanceID long, payID long, debtID long;
SELECT 
P_JOURNAL.AG_ID, 
Rep_tabel.AG_NAME, 
Sum(IIf(JP_CR="661" and MTC_ID <> [advanceID],P_JOURNAL.JP_SUM,0)) AS Выражение1, 
Sum(IIf(JP_DB="661" and MTC_ID <> [payID],P_JOURNAL.JP_SUM,0)) AS Выражение2, 
Sum(IIf(JP_CR="661" and MTC_ID <> [advanceID],P_JOURNAL.JP_SUM,0))-Sum(IIf(JP_DB="661",P_JOURNAL.JP_SUM,0)) AS Выражение3

FROM P_JOURNAL INNER JOIN Rep_tabel ON P_JOURNAL.AG_ID = Rep_tabel.agid

WHERE P_JOURNAL.JP_SUM<>0 AND P_JOURNAL.C_PERIOD=[pid] and MTC_ID <> [debtID]

GROUP BY P_JOURNAL.AG_ID, Rep_tabel.AG_NAME
ORDER BY Rep_tabel.AG_NAME
END
